name: Secrets Scan Action

on:
  pull_request:
    branches: [ main ]
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout aws git-secrets repo
        uses: actions/checkout@v2
        with:
          repository: awslabs/git-secrets

      - name: Install aws git-secrets
        run: sudo make install

      - name: Add AWS Configs
        run: git secrets --register-aws --global

      - name: Checkout ILMLF Code
        uses: actions/checkout@v2

      - name: Scan for secrets
        run: git secrets --scan